/*
 * language.h
 * */

#ifndef _LANGUAGE_H_
#define _LANGUAGE_H_

typedef char LANGUAGE;

#define VOICE_SEMANTIC_LANGUAGE_SET(DST, SRC) do{ strcpy((DST), (SRC)); }while(0)

typedef enum {
    VOICE_SEMANTIC_LANGUAGE_TYPE_NONE,
    VOICE_SEMANTIC_LANGUAGE_TYPE_ROOM,
    VOICE_SEMANTIC_LANGUAGE_TYPE_ACTION,
    VOICE_SEMANTIC_LANGUAGE_TYPE_OBJ,
    VOICE_SEMANTIC_LANGUAGE_TYPE_NONE
} VOICE_SEMANTIC_LANGUAGE_TYPE;

typedef enum {
    VOICE_SEMANTIC_ERROR = -1,
    VOICE_SEMANTIC_OK = 0
} VOICE_SEMANTIC_STATUS;
#endif /* _LANGUAGE_H_ */
